import { Editor, RustAnalyzer } from "@wcrichto/rust-editor";
import _ from "lodash";
import React, { useEffect, useState } from "react";

import { RunnableEditor, evalRust, scrollToBottom } from "./editor";

export interface Answer {
  errorExplanation: string;
  messageInterpretation: string;
  safetyViolation: string;
  functionFix: string;
}

export let Problem = ({
  snippet,
  next,
  ra,
  onStep,
}: {
  snippet: string;
  ra?: RustAnalyzer;
  next: (a: Answer) => void;
  onStep?: (step: number) => void;
}) => {
  let [step, setStep] = useState(0);

  let [errorMessage, setErrorMessage] = useState<string | undefined>(undefined);
  useEffect(() => {
    evalRust(snippet).then(result => setErrorMessage(result.stderr));
  });

  useEffect(scrollToBottom, [step]);

  let [answer] = useState<Answer>({
    errorExplanation: "",
    messageInterpretation: "",
    safetyViolation: "",
    functionFix: "",
  });

  let parts: ((finished: boolean) => React.ReactElement)[] = [
    finished => (
      <>
        <p>
          The following Rust function is rejected by the Rust compiler.{" "}
          <strong>
            In 1-2 sentences, explain why the compiler rejects this function.
          </strong>
        </p>
        <Editor
          disabled={true}
          contents={snippet}
          ra={!finished ? ra : undefined}
        />
        <p>
          <textarea
            className="response"
            disabled={finished}
            placeholder={"Write your answer here..."}
            onChange={e => {
              answer.errorExplanation = e.target.value;
            }}
          />
        </p>
      </>
    ),
    finished => (
      <>
        <p>
          Below is the actual error message generated by the Rust compiler.{" "}
          <strong>
            Does the error message say what you expected the error would be?
          </strong>{" "}
        </p>
        <pre className="error">{errorMessage || "(loading...)"}</pre>
        <p>
          <textarea
            disabled={finished}
            placeholder={"Write your answer here..."}
            onChange={e => {
              answer.messageInterpretation = e.target.value;
            }}
          />
        </p>
      </>
    ),
    finished => (
      <>
        <p>
          Assume that the compiler did NOT reject this function.{" "}
          <strong>
            Write a program that calls this function which would violate memory
            safety or cause a data race.
          </strong>{" "}
          If no such program exists, then explain in a comment why the function
          is actually safe.
        </p>
        <Editor
          contents={`fn main(){\n\n}`}
          disabled={finished}
          ra={!finished ? ra : undefined}
          onChange={(s: any) => {
            answer.safetyViolation = s;
          }}
        />
      </>
    ),
    _ => (
      <>
        <p>
          <strong>
            Fix this function to pass the compiler while preserving as much of
            its intent as possible.
          </strong>{" "}
          You can change any aspect of the function, including the type
          signature. You can click "Run" to get feedback from the compiler. You
          may use the{" "}
          <a
            href="https://doc.rust-lang.org/std/"
            target="_blank"
            rel="noreferrer"
          >
            standard library documentation
          </a>
          .
        </p>
        <RunnableEditor
          ra={ra}
          initialContents={snippet}
          onChange={s => {
            answer.functionFix = s;
          }}
        />
      </>
    ),
  ];

  return (
    <div className="problem">
      {parts
        .filter((_p, i) => i <= step)
        .map((part, i) => (
          <div className="part" key={i}>
            <h2>Part {i + 1}</h2>
            <div>{part(step != i)}</div>
            <button
              disabled={step != i}
              onClick={() => {
                onStep && onStep(step + 1);
                if (step == 3) next(answer);
                else setStep(step + 1);
              }}
            >
              Submit
            </button>
          </div>
        ))}
    </div>
  );
};
