name: CI
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          profile: minimal
      - uses: jetli/wasm-pack-action@v0.3.0
      - run: |
          cd packages/rust-editor
          ./setup-wasm.sh
      - uses: pnpm/action-setup@v2
      - run: | 
          git clone https://github.com/willcrichton/graco/
          cd graco && pnpm install && pnpm build && pnpm link --global
          cd ..
          graco init
          NODE_OPTIONS='--max-old-space-size=3584' graco build
          mkdir dist
          mv packages/ownership-inventory/dist dist/ownership-inventory
          mv packages/trpl-evaluator/dist dist/trpl-evaluator
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist